### ISSUE TITLE
How to parse the 'squeeze_net.caffemodel' to 'model.pkl' for python 3

### ISSUE THREAD

**Issue by wy1988** [yuanming-hu/fc4#11]
I use the python 3,and train the squeeze net by use caffe
so can you help me for parse the '.caffemodel' to 'pkl'...Tks!

**Comment by yt605155624** [comment]
pkl just a file which save a python dict ,you can  read the caffemodel ,save it as dict and save it .
caffe_model = 'VGG16/VGG_ILSVRC_16_layers.caffemodel'
deploy = 'VGG16/VGG_ILSVRC_16_layers_deploy.prototxt'
net = caffe.Net(deploy, caffe_model, caffe.TEST)  # 加载model和network
caffe 参数本身的格式也是numpu.ndarray
weights 和bias要分开
_dict = {}
for k, v in net.params.items():
	# print k, v[0].data.shape, v[1].data.shape
	_dict[k + '_weights'] = v[0].data
	_dict[k + '_bias'] = v[1].data
for k in _dict.keys():
	print k, _dict[k].shape
with open('vgg16.pkl','w') as f:
    pkl.dump(_dict, f, pkl.HIGHEST_PROTOCOL)
MODEL_PATH = 'data/VGG16/vgg16.pkl'

**Comment by yuanming-hu** [comment]
Hi guys,

Thanks for the question and the answer.
@wy1988 , if I understand correctly, you want to use caffe instead of tensorflow.
If that is the case, please consider use the original caffe model (https://github.com/DeepScale/SqueezeNet). `model.pkl` is the converted version for tensorflow to use.

**Comment by wy1988** [comment]
thank you ,I got this

**Comment by wy1988** [comment]
Another,how to understand the file like '8D5U5524_macbeth.txt'.
the value in the file what means!!tks

**Comment by yuanming-hu** [comment]
They should be coordinates of the chips on the color checker.

**Comment by hvudeshi** [comment]
How to convert from .pkl format to .caffemodel format?
