### ISSUE TITLE
BGR and RGB

### ISSUE THREAD

**Issue by yt605155624** [yuanming-hu/fc4#15]
The caffemodel needs BGR
When you write the datasets,you use cv2 and save the img as a mat ,so the mat is BGR ,and when you TEST a img,the img is read by cv2,so it is BGR, so I think  you should  not write 
alex_images = (tf.pow(images, 1.0 / config_get_input_gamma()) *
				               255.0)[:, :, :, ::-1]
::-1 in **fcn.py build_branches** here ,because the img is alreadly BGR,if not ,correct me~~

**Comment by yt605155624** [comment]
Another question is that in data_provider.py 
you write 			
			if self.is_training and AUGMENTATION:
				ldr, illum = augment(ldr, illum)
			else:
				ldr = ldr[:FCN_INPUT_SIZE, :FCN_INPUT_SIZE]
but in function augment ,you have write illumination = illumination[::-1] which means RGB->BGR,so if I use AUGMENTATION,the label I give to net is BGR and if not the label is RGB? WHY????
When test, the output of net is BGR OR RGB??(the three number's order confused me)

**Comment by yuanming-hu** [comment]
Just quick responses for now: 
 - Maybe Alexnet takes BGR, though I don't remember clearly
 - The output should probably be RGB, because the ground truth is probably RGB
