### ISSUE TITLE
Could you comment on my (Chinese) summary of this paper?

### ISSUE THREAD

**Issue by wy1988** [yuanming-hu/fc4#19]
This is my understanding. If there are mistakes, I hope you can correct me. tks!!
https://www.cnblogs.com/wangyong/p/9141075.html

**Comment by yuanming-hu** [comment]
谢谢！写的非常清楚。几点微小的建议：
 - “注：局部区域并不是一个patch，是其子集” 局部区域其实就是原图里面的一个矩形子集，说它是patch也没有太多不妥。在FC4中，FCN其实扫描了一系列均匀分布的sliding window里面的patch。
 - “如果希望预测的精度越高，则可以提供更多的patch，其覆盖率越高，精度自然也会更高，但效率会变低。” 其实FC4已经覆盖了全图，如果提供更多的patch帮助有限。这句话放在传统的patch-based的方法上更合适，如[Shi et al. 2016]。
 - "三重交叉验证，增强网络训练效果" 三重交叉验证是这个数据集规定的测试方法，并不是为了增强训练效果。实际上，把所有图喂进去训练效果会更好，只是我们没有测试数据来测试模型精度了。
 - “需要将图片中颜色丰富的color checker去掉以免干扰结果” 这个表述有一些不准确。去掉color checker是这个数据集要求的，因为只有训练/测试数据会有color checker，实际测试情况是不会有color checker的存在的。因此，这里去掉color checker并不是为了防止他干扰结果。实际上，如果不去掉，结果可能会更好，因为直接从color checker推断色彩信息比从图片的其它部分推断有效多了（ground truth就是从那里来的）。去掉color checker，是为了让结果能够让model generalize到没有color checker的实际情况

谢谢你的总结！如果有别的问题，欢饮来问我。

**Comment by yuanming-hu** [comment]
Closing this thread. Added a link to the blog at home page. Thanks again!
