### ISSUE TITLE
Can you provided the code how to correct the image and show it?

### ISSUE THREAD

**Issue by zyqgmzyq** [yuanming-hu/fc4#2]
When we  get the illuminant estimate using your experiment，How to correct it using the color we estimated and show the correct image? Can you share your code or method?

**Comment by yuanming-hu** [comment]
Sure, will do it later in an hour.

**Comment by zyqgmzyq** [comment]
Thank you !

**Comment by yuanming-hu** [comment]
Oh, I just realized I have to wait for the training to finish before I can do this. They are unlikely to finish before I go to bed so please wait for one day. Thanks!

**Comment by zyqgmzyq** [comment]
Ok！

**Comment by yuanming-hu** [comment]
Sorry for the delay. I updated the pretrained model and instructions about how to use it.
Please close this issue if it works for you, or let me know if there are other questions!

I have to go to bed now.. it's already 3 am :-)

**Comment by zyqgmzyq** [comment]
Thank you!
