### ISSUE TITLE
Some questions about confidence?

### ISSUE THREAD

**Issue by zyqgmzyq** [yuanming-hu/fc4#21]
Hi, I'm puzzled about the vis_confidence_color's compute method .Could you tell me about that?
![1528813005 1](https://user-images.githubusercontent.com/36949881/41295944-5727ce80-6e8e-11e8-9e3a-35e18812af97.jpg)

**Comment by yuanming-hu** [comment]
Thanks for the question. The thresholding functions are just for an arbitrary visualization. I forgot to remove these values during code release. They are actually used for an internal project. I think you can ignore them and I will soon remove them.
