### ISSUE TITLE
Cannot view the output images

### ISSUE THREAD

**Issue by shashi438** [yuanming-hu/fc4#26]
Hello! I'm having a bit of difficulty with viewing the processed images. It's mentioned that a directory outputs_cc would be created with the images but nothing was created other than outputs with the .pkl files.  Am I missing any step or is the code not updated? 

Many thanks!

**Comment by yuanming-hu** [comment]
Thanks for letting me know - I was so stupid to make the updates locally but forgot to push... Now it should work.
