### ISSUE TITLE
The test results are different from RAW of JPG images downloaded

### ISSUE THREAD

**Issue by realwill** [yuanming-hu/fc4#27]
hi, yuanming-hu:
   It's great job and thank you for your sharing the code.

在跑nus-8实验的时候发现，test的结果恢复出来的图片与数据集中的raw文件、jpg文件差别很大，数据集中的图片颜色更鲜艳，实验跑出来的结果明显偏灰、偏暗，我猜测数据集中的raw和jpg文件是经过了后期处理的图像，但在网页上没找到相关的说明，能否告知测试结果和数据集中数据差异的原因。
另：能否分享Illuminant Estimation for Color Constancy: Why spatial domain methods work and the role of the color distribution这篇论文的全文。

谢谢！

**Comment by yuanming-hu** [comment]
Could you share a test result? It's probably because of the missing gamma correction.

**Comment by realwill** [comment]
![canon159](https://user-images.githubusercontent.com/12739641/47889788-b052cb00-de86-11e8-934e-d04fa8078003.png)
![canon159_src](https://user-images.githubusercontent.com/12739641/47889793-b779d900-de86-11e8-8c74-b9c7f4f33648.png)

@yuanming-hu Thank you for your reply, as the pictures show, the upper left pic is recovered from png and the upper right pic is awb result with your train script, the third pic is given in the jpg.

**Comment by yuanming-hu** [comment]
Could you share me the input file so that I can reproduce? It looks like an exposure adjustment issue, rather a color constancy issue.

**Comment by realwill** [comment]
Canon1DsMkIII_0159.PNG is the input file

**Comment by realwill** [comment]
You can find it in the nus-8 dataset and it is taken by Canon1DsMkIII, anyway, it is not the problem of this pic, it is all the same of the nus-8 dataset.

**Comment by realwill** [comment]
![colorchecker_hu](https://user-images.githubusercontent.com/12739641/47890786-63252800-de8b-11e8-9205-00cd904a09f8.png)
![colorchecker_src](https://user-images.githubusercontent.com/12739641/47890788-63252800-de8b-11e8-8a43-3fb91e68972a.png)


Did you use exposure adjustment when you display the result? The upper two pics are showed in your paper, the lower two pics are the results use your released code.

**Comment by yuanming-hu** [comment]
They are indeed very dark...though exposure is not what a CC algorithm takes care of, I'm trying to figure out what makes them so dark. Just a minute...

**Comment by yuanming-hu** [comment]
I have no idea what's wrong but now it looks much better - I simply increased the exposure value by a factor of five.

**Comment by yuanming-hu** [comment]
I guess it is a visualization issue introduced in our further development after the paper is published. The angular errors are not affected though. Please pull and update.

**Comment by realwill** [comment]
Thanks a lot! I will try it!
Did you have other method more than the released code to make the results look better?

**Comment by realwill** [comment]
Thanks a lot! I will try it!
Did you have other method more than the released code to make the results look better?

**Comment by yuanming-hu** [comment]
Since this work studies color constancy, exposure values are just for visualization and can be arbitrary... I think you can always scale the image to make them look brighter or darker if you want.

**Comment by realwill** [comment]
ok, got it, thank you very much!
