### ISSUE TITLE
How can I get the "Shi's Re-processing of Gehler's Raw Dataset"

### ISSUE THREAD

**Issue by EmilySmile** [yuanming-hu/fc4#37]
How can I get the "Shi's Re-processing of Gehler's Raw Dataset".Is there another way I can get these database.

When i click the "Canon 1D" on the webpage , it shows that "The requested URL /~colour/data2/shi_gehler/png_canon1d.zip ws not found on this server"

**Comment by shuangzhou1028** [comment]
> How can I get the "Shi's Re-processing of Gehler's Raw Dataset".Is there another way I can get these database.
> 
> When i click the "Canon 1D" on the webpage , it shows that "The requested URL /~colour/data2/shi_gehler/png_canon1d.zip ws not found on this server"

Hi, how did you manage to obtain the dataset? I’m having the same issue. Any advice would be greatly appreciated. Thanks!
